item_name = input("Enter item name: ")
no_of_item = int(input("Enter item quantity: "))
cost = float(input("Enter item cost: "))
print("------------------------")
print("Product       :", item_name)
print("quantity      :", no_of_item)
print("Price         :", cost)
print("------------------------")
print("Total amount  :", cost * no_of_item)
print("------------------------")